### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Jrizzi1** [jasonfill/ColdFusion-ElasticSearch-Client#3]
Could you give a quick rundown of how you would install the client? i run an MVC coldbox app and dont know where to start

**Comment by jasonfill** [comment]
You will need to drop the code into your project or create a mapping to the files.  Then you can use the Getting Started section of the readme to instantiate the Client object.

**Comment by amaryassa** [comment]
Hello, 3 years after you created the CF-ES client.
Currently I am on Coldfusion 11 and Elasticsearch 5.4 (beginner).
And the client does not work, if you can help me please.
